config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  resources :articles
  resources :users
  
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: {minimum: 6}
  validates :description, presence: true, length: {minimum: 20}

end

app/models/user.rb
class User < ApplicationRecord
  before_save {self.email=email.downcase}
  has_many :articles, dependent: :destroy

  validates :username, presence: true, uniqueness: { case_sensitive: false },  length: {minimum: 3}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,uniqueness: { case_sensitive: false }, length: { maximum: 105 }, format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end
  def require_user
    if !logged_in?
      #render html: helpers.tag.strong('You can edit or delete only your Account ')
      flash[:error] = "You must login first...."
      redirect_to login_path
    end

  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    
    @article = Article.new
  end

  def create
    @article=Article.new(params.require(:article).permit(:title, :description))
    @article.user=current_user
    if @article.save
      flash[:notice] = "Article was created successfully."
      redirect_to @article
    else
      flash[:error]= "There is a problem in article creation."
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(params.require(:article).permit(:title, :description))
      flash[:notice] = "Article was updated successfully."
      redirect_to @article
    else
      flash[:alert]="There is problem in updation of article."
      render 'edit'
    end
  end

  def destroy
    @article=Article.find(params[:id])
    @article.destroy
    flash[:notice] ="Article was deleted successfully."
    redirect_to articles_path
  end

  private
  def require_same_user
    @article=Article.find(params[:id])
    if current_user != @article.user
      flash[:error] = "You can only edit or delete your own article"
      redirect_to @article
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      
      redirect_to user, notice: "logged in successfully"
    else
      flash.now[:alert] = "Please check your email and password"
      render 'new'
    end
  end

  def destroy
   session[:user_id] = nil
   flash[:notice] = "Logged out"
   redirect_to root_path
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  def new
    @user=User.new
  end

  def create
    @user=User.new(params.require(:user).permit(:username, :email, :password))

    if @user.save
      session[:user_id] = @user.id
      flash[:notice]= "You have successfully signed up"
      redirect_to @user
    else
      flash[:error]="There is a problem in signing up"
      render :new
    end
  end

  def index
    @user=User.all
  end

  def show
    @user = User.find(params[:id])
    @article=@user.articles
  end
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(params.require(:user).permit(:username, :email, :password))
      flash[:notice] = "User was updated successfully."
      redirect_to @user
    else
      flash[:notice] = "There is a problem in editing"
      render :edit
    end
  end

  def destroy
   @user=User.find(params[:id])
   @user.destroy
   session[:user_id] = nil
   flash[:notice] = "Account and all associated articles successfully deleted"
   redirect_to articles_path
  end
  private
  def require_same_user
    @user=User.find(params[:id])
    if current_user != @user
      #render html: helpers.tag.strong('You can edit or delete only your Account ')
      flash[:notice] = "You can edit/delete your account only!"
      redirect_to @user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/articles/edit.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<%= link_to "ARTICLES", root_path, class: "navbar-brand", id: "logo" %>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
    <%= link_to "Articles Index", articles_path, class: "nav-link" %>
    </li>
    <li class="nav-item active">
    <%= link_to "Users Index", users_path, class: "nav-link" %>
    </li>
    <% if logged_in? %>
      <li class="nav-item active">
        <%= link_to current_user.username, user_path(current_user), class: "nav-link" %>
      </li>   
      <li class="nav-item active">
        <%= link_to 'Logout', logout_path, method: :delete, class: "nav-link" %>
      </li> 
    <% else %> 
      <li class="nav-item active">
        <%= link_to 'Log-in', login_path, class: "nav-link" %>
      </li> 
      <li class="nav-item active">
        <%= link_to 'Signup', signup_path, class: "nav-link" %>
      </li> 

    <% end %>
 </ul>
</div>
</nav>
<div class="container">
<div class="jumbotron">
<h1> Edting article: <%=@article.title%></h1>
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %> 
</div> 
<% if @article.errors.any? %>
  <h2>the following are errors</h2>
  <ul>
    <% @article.errors.full_messages.each do |m| %>
      <li><%= m%></li>
    <% end %>
  </ul>
<% end %>

<%= form_with(model: @article, local: true) do |f| %>

  <div>
    <%= f.label :title %>
    <br>
    <br>
    <%= f.text_field :title %>
    <br>
    <br>
  </div>

  <div>
    <%= f.label :description %>
    <br>
    <br>
    <%= f.text_area :description %>
    <br>
    <br>
  </div>

  <div>
    <%= f.submit %>
  </div>

<% end %>
<br>
<br>
<div>
        <%= link_to ' Cancel and return to articles listing ', articles_path, class: "text-info" %>
</div>
</div>
</div>

app/views/articles/index.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<%= link_to "ARTICLES", root_path, class: "navbar-brand", id: "logo" %>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
    <%= link_to "Articles Index", articles_path, class: "nav-link" %>
    </li>
    <li class="nav-item active">
    <%= link_to "Users Index", users_path, class: "nav-link" %>
    </li>
    <% if logged_in? %>
      <li class="nav-item active">
        <%= link_to current_user.username, user_path(current_user), class: "nav-link" %>
      </li>   
      <li class="nav-item active">
        <%= link_to 'Logout', logout_path, method: :delete, class: "nav-link" %>
      </li> 
    <% else %> 
      <li class="nav-item active">
        <%= link_to 'Log-in', login_path, class: "nav-link" %>
      </li> 
      <li class="nav-item active">
        <%= link_to 'Signup', signup_path, class: "nav-link" %>
      </li> 

    <% end %>
 </ul>
</div>
</nav>

<div class="container">
<div class="jumbotron">
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name %>  alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %> 
</div> 
<table class="table table-hover">
  <tr>
    <th><h3><b>Title of Article</b></h3></th>
    <th><h3><b>Description of Article</b></h3></th>
    <th><h3><b>Created By</b></h3></th>&nbsp;
    <th colspan="3"><h3><b>Actions on Articles </b></h3>  </th>
  </tr>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%=article.title%> &nbsp;&nbsp;</td>
        <td>  <%=article.description%>&nbsp;&nbsp;</td>
        <td><%= link_to article.user.username, user_path(article.user) %>&nbsp;&nbsp;</td>
        
        <td><%= link_to 'Show   ', article_path(article)%>&nbsp;&nbsp;</td>
        <% if logged_in? && article.user == current_user %>
          <td><%= link_to 'edit   ', edit_article_path(article)%>&nbsp;&nbsp;</td>
          

          <td><%= link_to 'delete', article_path(article), method: :delete, data: {confirm: "Are you sure?"} %></td>
          
        <% end %>
       </tr>
      <%end%>
  </tbody>
</table>
<br>
<br>
<br>

<% if logged_in? %>
<p class="lead">
    
     <a class="btn btn-primary btn-lg" href="articles/new" role="button" >create new article</a>
     
   
  </p>
  <% end %>
</div>
</div>

app/views/articles/new.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<%= link_to "ARTICLES", root_path, class: "navbar-brand", id: "logo" %>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
    <%= link_to "Articles Index", articles_path, class: "nav-link" %>
    </li>
    <li class="nav-item active">
    <%= link_to "Users Index", users_path, class: "nav-link" %>
    </li>
    <% if logged_in? %>
      <li class="nav-item active">
        <%= link_to current_user.username, user_path(current_user), class: "nav-link" %>
      </li>   
      <li class="nav-item active">
        <%= link_to 'Logout', logout_path, method: :delete, class: "nav-link" %>
      </li> 
    <% else %> 
      <li class="nav-item active">
        <%= link_to 'Log-in', login_path, class: "nav-link" %>
      </li> 
      <li class="nav-item active">
        <%= link_to 'Signup', signup_path, class: "nav-link" %>
      </li> 

    <% end %>
 </ul>
</div>
</nav>
<div class="container">
<div class="jumbotron">
<h1>Creating New Article: <%=@article.title%></h1>
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name %>  alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %> 
</div> 
<% if @article.errors.any? %>
  <h2>the following are errors</h2>
  <ul>
    <% @article.errors.full_messages.each do |m| %>
      <li><%= m%></li>
    <% end %>
  </ul>
  
<% end %>

<%= form_with(model: @article, local: true) do |f| %>

  <div>
    <%= f.label :title %>
    <br>
    <br>
    <%= f.text_field :title %>
    <br>
    <br>
  </div>

  <div>
    <%= f.label :description %>
    <br>
    <br>
    <%= f.text_area :description %>
    <br>
    <br>
  </div>

  <div>
    <%= f.submit %>
  </div>

<% end %>
<br>
<br>
<div>
        <%= link_to ' Cancel and return to articles listing ', articles_path, class: "text-info" %>
</div>
</div>
</div>

app/views/articles/show.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<%= link_to "ARTICLES", root_path, class: "navbar-brand", id: "logo" %>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
    <%= link_to "Articles Index", articles_path, class: "nav-link" %>
    </li>
    <li class="nav-item active">
    <%= link_to "Users Index", users_path, class: "nav-link" %>
    </li>
    <% if logged_in? %>
      <li class="nav-item active">
        <%= link_to current_user.username, user_path(current_user), class: "nav-link" %>
      </li>   
      <li class="nav-item active">
        <%= link_to 'Logout', logout_path, method: :delete, class: "nav-link" %>
      </li> 
    <% else %> 
      <li class="nav-item active">
        <%= link_to 'Log-in', login_path, class: "nav-link" %>
      </li> 
      <li class="nav-item active">
        <%= link_to 'Signup', signup_path, class: "nav-link" %>
      </li> 

    <% end %>
 </ul>
</div>
</nav>
<div class="container">
<div class="jumbotron">
<h2><b>Showing article details  </b></h2>
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %> 
</div> 

<ul>
  <li><b>Title:</b> <%= @article.title %></li>
  <br>
  <br>
  <li><b>Description:</b> <%= @article.description %> </li>
  <br><br>
  <li><b>Created by: </b> <%= @article.user.username %> </li>
</ul>
<br><br>
<% if logged_in? && current_user == @article.user %>
<p class="lead">
<%= link_to 'Edit Article', edit_article_path(@article)%>&nbsp;&nbsp;
<%= link_to 'Delete Article', article_path(@article), method: :delete, data: {confirm: "Are you sure?"} %>
  </p>
  <% end %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<%= link_to "ARTICLES", root_path, class: "navbar-brand", id: "logo" %>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
    <%= link_to "Articles Index", articles_path, class: "nav-link" %>
    </li>
    <li class="nav-item active">
    <%= link_to "Users Index", users_path, class: "nav-link" %>
    </li>
    <% if logged_in? %>
      <li class="nav-item active">
        <%= link_to current_user.username, user_path(current_user), class: "nav-link" %>
      </li>   
      <li class="nav-item active">
        <%= link_to 'Logout', logout_path, method: :delete, class: "nav-link" %>
      </li> 
    

    <% end %>
 </ul>
</div>
</nav>

<div class="container">
<div class="jumbotron">
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name %>  alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %> 
</div> 
  <h1 class="display-4">Articles-Task1</h1>
  <p class="lead">This is the home-page for Articles .</p>
  <hr class="my-4">
  <% if !logged_in? %>
  <p class="lead">
  <p>You can signup or login here.</p>
  <br>
  <br>
  
    
     <a class="btn btn-primary btn-lg" href="login" role="button" >Login</a>&nbsp;&nbsp;
     <a class="btn btn-primary btn-lg" href="signup" role="button">Signup!</a>
   
  </p>
  <% else %>
      <h3>Thank you for using this website... Hope you have enjoyed it..</h3>
  <% end %>
</div>
</div>

app/views/users/edit.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<%= link_to "ARTICLES", root_path, class: "navbar-brand", id: "logo" %>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
    <%= link_to "Articles Index", articles_path, class: "nav-link" %>
    </li>
    <li class="nav-item active">
    <%= link_to "Users Index", user_path, class: "nav-link" %>
    </li>
    <% if logged_in? %>
      <li class="nav-item active">
        <%= link_to current_user.username, user_path(current_user), class: "nav-link" %>
      </li>   
      <li class="nav-item active">
        <%= link_to 'Logout', logout_path, method: :delete, class: "nav-link" %>
      </li> 
    <% else %> 
      <li class="nav-item active">
        <%= link_to 'Log-in', login_path, class: "nav-link" %>
      </li> 
      <li class="nav-item active">
        <%= link_to 'Signup', signup_path, class: "nav-link" %>
      </li> 

    <% end %>
 </ul>
</div>
</nav>
<div class="container">
<div class="jumbotron">
<h1>Editing the user details</h1>
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %> 
</div> 
<div>
<% if @user.errors.any? %>
  <h2>the following are errors</h2>
  <ul>
    <% @user.errors.full_messages.each do |m| %>
      <li><%= m %></li>
    <% end %>
  </ul>
<% end %>
</div>
<%= form_with(model: @user, local: true) do |f| %>

  <div>
    <%= f.label :username %>
    <br>
    <br>
    <%= f.text_field :username %>
    <br>
    <br>
  </div>

  <div>
    <%= f.label :email %>
    <br>
    <br>
    <%= f.email_field :email %>
    <br>
    <br>
  </div>

  <div>
    <%= f.label :password %>
    <br>
    <br>
    <%= f.password_field :password %>
    <br>
    <br>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>
<br><br>
<%= link_to 'Cancel and return to users listing ', users_path %>
</div>
</div>

app/views/users/index.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<%= link_to "ARTICLES", root_path, class: "navbar-brand", id: "logo" %>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
    <%= link_to "Articles Index", articles_path, class: "nav-link" %>
    </li>
    <li class="nav-item active">
    <%= link_to "Users Index", users_path, class: "nav-link" %>
    </li>
    <% if logged_in? %>
      <li class="nav-item active">
        <%= link_to current_user.username, user_path(current_user), class: "nav-link" %>
      </li>   
      <li class="nav-item active">
        <%= link_to 'Logout', logout_path, method: :delete, class: "nav-link" %>
      </li> 
    <% else %> 
      <li class="nav-item active">
        <%= link_to 'Log-in', login_path, class: "nav-link" %>
      </li> 
      <li class="nav-item active">
        <%= link_to 'Signup', signup_path, class: "nav-link" %>
      </li> 

    <% end %>
 </ul>
</div>
</nav>
<div class="container">
<div class="jumbotron">
<table class="table table-hover">
  <tr>
    <th><h3><b>User Name</b></h3></th>
    <th><h3><b>User Email</b></h3></th>
    <th><h3><b>No of Articles Created</b></h3></th>
    <th colspan="3"><h3><b>Actions on User</b></h3></th>
  </tr>
  <tbody>
    <% @user.each do |user| %>
      <tr>
        <td><%= link_to user.username, user_path(user) %>&nbsp;&nbsp;</td>
        <td>  <%=user.email%>&nbsp;&nbsp;</td>
        <td><%=user.articles.count%>&nbsp;&nbsp;</td>
        <td><%= link_to 'Show', user_path(user)%></td>
        <% if logged_in? and user == current_user %>
          <td><%= link_to 'edit', edit_user_path(user)%></td>
          <td><%= link_to 'delete', user_path(user), method: :delete, data: {confirm: "Are you sure?"} %></td>
        <% end %>
      </tr>
      <%end%>
  </tbody>
</table>
<br>
<br>
<br>
<% if logged_in? %>
<p class="lead">
    
     <a class="btn btn-primary btn-lg" href="users/new" role="button" >Create new User</a>
     
   
  </p>
  <% end %>
</div>
</div>

app/views/users/show.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<%= link_to "ARTICLES", root_path, class: "navbar-brand", id: "logo" %>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
    <%= link_to "Articles Index", articles_path, class: "nav-link" %>
    </li>
    <li class="nav-item active">
    <%= link_to "Users Index", users_path, class: "nav-link" %>
    </li>
    <% if logged_in? %>
      <li class="nav-item active">
        <%= link_to current_user.username, user_path(current_user), class: "nav-link" %>
      </li>   
      <li class="nav-item active">
        <%= link_to 'Logout', logout_path, method: :delete, class: "nav-link" %>
      </li> 
    <% else %> 
      <li class="nav-item active">
        <%= link_to 'Log-in', login_path, class: "nav-link" %>
      </li> 
      <li class="nav-item active">
        <%= link_to 'Signup', signup_path, class: "nav-link" %>
      </li> 

    <% end %>
 </ul>
</div>
</nav>
<div class="container">
<div class="jumbotron">
<h2><u><b>Showing User Details </b></u> </h2>
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name %>  alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %> 
</div> 

<br>
<ul>
  <li><h4><b>User_name:</b> &nbsp;<%= @user.username %></h4></li>

  <li><h4><b>Email:</b> &nbsp;<%= @user.email %> </b></h4></li>
  <br>
  <% if logged_in? && @user == current_user %>
    <%= link_to "Edit your profile", edit_user_path(@user) %> &nbsp;
  <% end %>

  <%= link_to "user index", users_path %>
</ul>
<% if @user.articles.count > 0 %>
<h3><u><b> Articles by <%=@user.username%></b></u></h3>
<table class="table table-hover">
  <tr>
    <th><h3><b>Title of Article</b></h3></th>
    <th><h3><b>Description of Article</b></h3></th>
    
    <th colspan="3"><h3><b>Actions on Articles </b></h3>  </th>
  </tr>
  <tbody>
    <% @user.articles.each do |article| %>
      <tr>
        <td><%=article.title%> &nbsp;&nbsp;</td>
        <td>  <%=article.description%>&nbsp;&nbsp;</td>
        
        
        <td><%= link_to 'Show   ', article_path(article)%>&nbsp;&nbsp;</td>
        <% if logged_in? && article.user == current_user %>
          <td><%= link_to 'edit   ', edit_article_path(article)%>&nbsp;&nbsp;</td>
          

          <td><%= link_to 'delete', article_path(article), method: :delete, data: {confirm: "Are you sure?"} %></td>
          
        <% end %>
       </tr>
      <%end%>
  </tbody>
</table>
<% else %>
      <h3> Articles are not yet Created </h3>
<% end %>
<br><br>
<% if logged_in? && @user == current_user %>
<p class="lead">
    
     <a class="btn btn-primary btn-lg" href="articles/new" role="button" >create new article</a>
     
   
  </p>
  <% end %>

</div>
</div>